#!/bin/bash
THEME=$1
VERSION=$2
UPSALE_THEME=$3

rm -rf ~/git/build/$THEME/$VERSION
cd ~/git/source/circus-quacktape
git pull
cp ~/git/source/circus-quacktape/lib/clown/renderCobalt.js ~/git/build/ringmaster/quacktape/lib/clown/renderCobalt.js
cd ~/git/build/ringmaster
node app/test-clown.js $THEME $VERSION $UPSALE_THEME
cp ~/git/build/auth.txt ~/git/build/$THEME/auth.txt
cp ~/git/build/cert.pem ~/git/build/$THEME/cert.pem
cp ~/git/build/key.pem ~/git/build/$THEME/key.pem
cp ~/git/build/DB.json ~/git/build/$THEME/DB.json
cp ~/git/build/region.txt ~/git/build/$THEME/region.txt
cd ~/git/build/$THEME/$VERSION
node app/exec.js